### ISSUE TITLE
How to attach a node to existing xml

### ISSUE THREAD

**Issue by francescobarbera** [oozcitak/xmlbuilder2#10]
We have a question about creating and attaching nodes at different times.

What we are trying to do is to create a sub-node in a function and attach to the main tree in a second time.

```
const { create, fragment } = require("xmlbuilder2");

const mainNode = create({ version: "1.0", encoding: "utf-8" })
    .ele("element_a")
    .ele("element_b")
    .txt("b_value");

const createSubNode = () =>
    fragment()
        .ele("element_c")
        .txt("c_value")
        .up();

const nodeToAttach = createSubNode();

const bNode = mainNode.find(n => n.node.nodeName === "element_b", true, true);

// we have to attach nodeToAttach after bnode
bNode.ele(nodeToAttach);
```

But we haven't found a solution because of all the methods parameters are JSON and not nodes. In our use case, we could not use JSON because attributes order is essential.

Is there a way to solve our problem?

**Comment by oozcitak** [comment]
Did you try the `import` function?
https://oozcitak.github.io/xmlbuilder2/node-creation-functions.html#import

**Comment by francescobarbera** [comment]
perfect, is what we are looking for, maybe during our tests, we wrongly used this method.

**Comment by oozcitak** [comment]
Also since you mentioned; object order is preserved done ES2015: https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/&ved=2ahUKEwjRg_jSg6noAhWM16QKHUxXCZkQFjACegQIARAB&usg=AOvVaw3XQwXwYKsjTS896Sjs5fe3

**Comment by guerrap** [comment]
> Also since you mentioned; object order is preserved since ES2015: https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/

So the order is guaranteed when we create a document with `fragment` or `create` and pass the input as an `object`, right?
I'm asking you this because looking at [this issue](https://github.com/oozcitak/xmlbuilder-js/issues/191#issuecomment-440996897), it seems that the order defined in the input object can't be preserved when creating documents. Am I missing something?

Also how this impacts performances when compared with the builder API?

**Comment by oozcitak** [comment]
> I'm asking you this because looking at this issue, it seems that the order defined in the input object can't be preserved when creating documents.

I always believed object order was undefined in JS however I later learned that when ES2015 came out object it guaranteed insertion for string keys. Number and symbol keys get moved around but that doesn't concern us since we can't have numbers as element names in the first place. So if you are able to use a new version of node, you should be good.

> Also how this impacts performances when compared with the builder API?

Performance-wise there is a small penalty for parsing the object and checking keys for node types (those are a handful of string comparisons) so `ele` and friends should be a bit faster. I would be surprised if the difference would be much though.

I think most CPU cycles will be used by the `import` function if you will use it frequently because it needs to clone the imported XML tree. If performance is a concern you may be better of not using `import` at all.
