### ISSUE TITLE
Return type of convert requires casting when used in TypeScript

### ISSUE THREAD

**Issue by oozcitak** [oozcitak/xmlbuilder2#14]
From: https://github.com/oozcitak/xmlbuilder-js/issues/147#issuecomment-605225855

**Comment by leafac** [comment]
@oozcitak: Thanks for working on this.

I tried the following:

```ts
xmlbuilder2.convert(`<a>b</a>`, { format: "object" }).a;
```

And the TypeScript compiler complains that:

```
error TS2339: Property 'a' does not exist on type 'XMLSerializedAsObject | XMLSerializedAsObjectArray'.
  Property 'a' does not exist on type 'XMLSerializedAsObjectArray'.
```

That’s because the return type of `convert()` is declared to be either an object **or** an array. But I think the actual returned value is always an object and never an array. For example, the following fails:

```ts
xmlbuilder2.convert(`<a>b</a><c>d</c>`, { format: "object" });
// Error: The operation would yield an incorrect node tree. Document already has a document element node. Node is c.
```

As it stands, I still have to cast the return of `convert()` with `as any`.

Am I doing something wrong? Or could the return type of `convert()` be only `XMLSerializedAsObject`?

**Comment by oozcitak** [comment]
No you are right, it can never return an array. I'll look into it.

**Comment by leafac** [comment]
After thinking some more about it, the truth is that even if convert() returned an object, every property of that object could be an object or an array, so the benefit is limited. It may better to leave it as it is. Either you’re safe and always check for arrays, or you use a type assertion like I mentioned (as any).
