### ISSUE TITLE
HTML characters are wrongly escaped

### ISSUE THREAD

**Issue by adarshmadrecha** [oozcitak/xmlbuilder2#55]
**Describe the bug**
When using escaped characters like ` &#13;` and `&#10;` in Js, they are converted to wrong characters in XML like `&amp;#13;` and `&amp;#10;`
Because of this, I am not able to add `CRLF`. 

**To Reproduce**
``` js
const finalObj = {
     ENVELOPE: {
       HEADER: {
         TALLYREQUEST: "Line One &#13;&#10; Line Two",
       },
    };
const doc = create(finalObj);
const xml = doc.end({ prettyPrint: true });
```

``` xml
<!-- Currently it's generated like this  -->
<?xml version="1.0"?>
<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Line One &amp;#13;&amp;#10; Line Two</TALLYREQUEST>
  </HEADER>
</ENVELOPE>
```

``` xml
<!-- What I Expect to generate  -->
<?xml version="1.0"?>
<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Line One &#13;&#10; Line Two</TALLYREQUEST>
  </HEADER>
</ENVELOPE>
```

**Expected behavior**
` &#13;` should remain ` &#13;`  and not get converted to `&amp;#13;`

**Version:**
 - node.js: [12.18.3]
 - xmlbuilder2 [2.4.0]

**Additional context**
The legacy application does not understand `\n`. Hence I want to use these characters (` &#13;` and `&#10;`) as is.

**Comment by oozcitak** [comment]
This is an XML builder not an HTML document builder. So `&#13;` has no special meaning in XML context. This behavior is expected. 

That being said I understand the use case for your issue, so I have a suggestion. I am working on custom document serializers, which will allow you to convert your document into whatever format you like. This will allow you to not escape HTML characters. The issue is here if you would like to keep track: https://github.com/oozcitak/xmlbuilder2/issues/47
